##订单分配逻辑
rule AssignOrder
when
    $address contains 北京 or $address contains 北京市;
then
    $user:order(mihome=北京仓)
    
when 
    $address contains 上海
then
    $user:order(mihome=上海仓)    
    
when 
    $user:order(mihome==上海仓);$user:order(price>100)
then
    $user:order(price=$user:order:price-10)

when
    $user:order(mihome==北京仓);$user:order(price<90)
then
    $address=$user:order:id . $address
end
    
